name: Tests

on:
  push:
    branches:
    - main
    - master
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' && github.ref != 'refs/heads/main' }}

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Run tests
      run: |
        #!/usr/bin/env bash
        set -euo pipefail

        modified_files=$(git diff --diff-filter=d --name-only HEAD^ HEAD)
        echo "$(echo $modified_files | wc -l | xargs) modified file(s) (excluding deleted files; showing at most 20):"
        echo "$modified_files" | sort | head -n 20
        echo "--------------------------------------------------------------------------------"

        # TODO: Run tests only for modified files
        ./scripts/tests/run_tests.sh
